<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WINDOWS-R8SKFHD" name="Validating Assertions" tests="1" failures="1" timestamp="24 Mar 2022 15:02:59 GMT" time="172.992" errors="0">
  <testcase name="feature" time="170.878" classname="cucmberOptions.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [Account already exists with this mobile number. Please login.] but found [Invalid mobile number.]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Account already exists with this mobile number. Please login.] but found [Invalid mobile number.]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: java.lang.AssertionError: expected [Account already exists with this mobile number. Please login.] but found [Invalid mobile number.]
	at stepDefinations.stepDefination.verify_that_user_is_successfully_logged_in(stepDefination.java:97)
	at âœ½.Then Verify that user is successfully logged in(src/test/java/features/Login.feature:8)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Validating Assertions -->
